language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  slack: deploys-workspace:XLMgSfa8d86YRkb93JwEQhUX
  email:
    recipients:
      - borisvargaspaucara@gmail.com
      - bvargas7@umsa.bo
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key:  79b9ce9b-d3ec-466f-9df4-f0a4bfdddca8 # desde heroku
  app: platzi-store-b
  on:
    repo: borisvargas/platzi-store-backend
# fin file travis